version: 2.1
setup: true

change-filters: &change-filters
  branches:
    ignore: master

trunk-filters: &trunk-filters
  branches:
    only: master

orbs:
  continuation: circleci/continuation@1.1.0
  security: studion/security@2.1.0
  shellcheck: circleci/shellcheck@3.4.0

jobs:
  scan-dockerfile:
    executor: security/node
    steps:
      - checkout
      - security/scan_dockerfile
  detect-image-changes:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Install Yq
          command: ./scripts/install-yq.sh
      - run:
          name: Detect image changes
          command: ./scripts/detect-image-changes.sh
      - continuation/continue:
          configuration_path: .circleci/push-image.yml

workflows:
  scan-and-detect:
    jobs:
      - shellcheck/check:
          filters: *change-filters
      - scan-dockerfile:
          filters: *change-filters
      - security/detect_secrets_git:
          filters: *change-filters
      - security/detect_secrets_dir:
          filters: *trunk-filters
      - detect-image-changes:
          filters: *trunk-filters
          requires:
            - shellcheck/check
            - scan-dockerfile
            - security/detect_secrets_git
            - security/detect_secrets_dir
